#!/usr/bin/env python3
"""Aggregate parallel encoder TIMD usage shards into one CSV per sequence/QP."""

from __future__ import annotations

import argparse
import csv
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, List, Mapping, MutableMapping, Sequence, Tuple


COUNT_FIELDS: Tuple[str, ...] = (
    "slices",
    "ctus",
    "luma_cus",
    "intra_pred_luma_cus",
    "timd_total",
    "timd_normal",
    "timdsad",
    "timd_merge",
    "timd_invalid",
    "timd_merge_available",
    "timd_merge_not_selected",
    "timd_merge_flag_coded",
    "timd_merge_flag_zero",
    "timd_merge_flag_one",
    "luma_samples",
    "intra_pred_luma_samples",
    "timd_samples",
    "timd_normal_samples",
    "timdsad_samples",
    "timd_merge_samples",
    "timd_invalid_samples",
    "timd_merge_available_samples",
    "timd_merge_not_selected_samples",
    "timd_merge_flag_coded_samples",
    "timd_merge_flag_zero_samples",
    "timd_merge_flag_one_samples",
)

IDENTITY_FIELDS: Tuple[str, ...] = (
    "sequence",
    "qp",
    "layer_id",
    "shard",
    "frame_skip",
    "poc",
    "source_frame",
)

MODE_FIELDS: Tuple[Tuple[str, str, str], ...] = (
    ("TIMD", "timd_normal", "timd_normal_samples"),
    ("TIMDSAD", "timdsad", "timdsad_samples"),
    ("TIMDMerge", "timd_merge", "timd_merge_samples"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Read .shards generated by EncoderApp and write "
            "<output-root>/<sequence>/QP<qp>.csv summaries."
        )
    )
    parser.add_argument(
        "--input-root",
        type=Path,
        default=Path("timd_usage_stats"),
        help="statistics root containing .shards (default: timd_usage_stats)",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=None,
        help="summary root (default: same as --input-root)",
    )
    parser.add_argument(
        "--keep-overlaps",
        action="store_true",
        help="count overlapping source frames from every RAS shard instead of deduplicating them",
    )
    parser.add_argument(
        "--expected-qps",
        default="22,27,32,37",
        help="comma-separated QPs expected for each sequence; missing QPs are warnings (default: 22,27,32,37)",
    )
    return parser.parse_args()


def as_int(row: Mapping[str, str], field: str, path: Path, line: int) -> int:
    try:
        return int(row[field])
    except (KeyError, TypeError, ValueError) as error:
        raise ValueError(f"{path}:{line}: invalid integer field {field!r}") from error


def read_shards(shard_root: Path) -> List[Dict[str, object]]:
    paths = sorted(shard_root.glob("*/QP*/*.csv"))
    if not paths:
        raise FileNotFoundError(f"no TIMD statistic shards found below {shard_root}")

    rows: List[Dict[str, object]] = []
    for path in paths:
        with path.open("r", encoding="utf-8", newline="") as stream:
            reader = csv.DictReader(stream)
            if reader.fieldnames is None:
                raise ValueError(f"{path}: missing CSV header")
            required = set(IDENTITY_FIELDS) | set(COUNT_FIELDS) | {"schema_version", "bitstream"}
            missing = required - set(reader.fieldnames)
            if missing:
                raise ValueError(f"{path}: missing fields: {', '.join(sorted(missing))}")

            for line, raw in enumerate(reader, start=2):
                if as_int(raw, "schema_version", path, line) != 2:
                    raise ValueError(f"{path}:{line}: unsupported schema_version")

                row: Dict[str, object] = {
                    "sequence": raw["sequence"],
                    "shard": raw["shard"],
                    "bitstream": raw["bitstream"],
                    "source_path": str(path),
                }
                for field in ("qp", "layer_id", "frame_skip", "poc", "source_frame") + COUNT_FIELDS:
                    row[field] = as_int(raw, field, path, line)

                category_total = (
                    int(row["timd_normal"])
                    + int(row["timdsad"])
                    + int(row["timd_merge"])
                    + int(row["timd_invalid"])
                )
                sample_total = (
                    int(row["timd_normal_samples"])
                    + int(row["timdsad_samples"])
                    + int(row["timd_merge_samples"])
                    + int(row["timd_invalid_samples"])
                )
                if category_total != int(row["timd_total"]):
                    raise ValueError(f"{path}:{line}: TIMD CU categories do not sum to timd_total")
                if sample_total != int(row["timd_samples"]):
                    raise ValueError(f"{path}:{line}: TIMD sample categories do not sum to timd_samples")
                if int(row["timd_total"]) > int(row["intra_pred_luma_cus"]):
                    raise ValueError(f"{path}:{line}: timd_total exceeds intra_pred_luma_cus")
                if int(row["timd_merge_flag_coded"]) != (
                    int(row["timd_merge_flag_zero"]) + int(row["timd_merge_flag_one"])
                ):
                    raise ValueError(f"{path}:{line}: coded merge flags do not equal zero plus one flags")
                if int(row["timd_merge_flag_one"]) != int(row["timd_merge"]):
                    raise ValueError(f"{path}:{line}: merge flag-one count does not equal selected TIMD-Merge count")
                if int(row["timd_merge_available"]) != (
                    int(row["timd_merge_not_selected"]) + int(row["timd_merge"])
                ):
                    raise ValueError(f"{path}:{line}: available merge candidates do not split into lost and selected")
                if int(row["timd_merge_flag_zero"]) > int(row["timd_merge_not_selected"]):
                    raise ValueError(f"{path}:{line}: zero merge flags exceed non-selected merge candidates")
                if int(row["timd_merge_flag_coded_samples"]) != (
                    int(row["timd_merge_flag_zero_samples"]) + int(row["timd_merge_flag_one_samples"])
                ):
                    raise ValueError(f"{path}:{line}: coded merge-flag samples do not equal zero plus one samples")
                if int(row["timd_merge_flag_one_samples"]) != int(row["timd_merge_samples"]):
                    raise ValueError(f"{path}:{line}: merge flag-one samples do not equal selected TIMD-Merge samples")
                if int(row["timd_merge_available_samples"]) != (
                    int(row["timd_merge_not_selected_samples"]) + int(row["timd_merge_samples"])
                ):
                    raise ValueError(f"{path}:{line}: available merge samples do not split into lost and selected")
                rows.append(row)
    return rows


def measurement_signature(row: Mapping[str, object]) -> Tuple[int, ...]:
    return tuple(int(row[field]) for field in COUNT_FIELDS)


def select_rows(
    rows: Sequence[Mapping[str, object]], keep_overlaps: bool
) -> Tuple[List[Mapping[str, object]], int, int, int]:
    unique_keys = {(int(row["layer_id"]), int(row["source_frame"])) for row in rows}
    if keep_overlaps:
        return list(rows), len(unique_keys), 0, 0

    selected: Dict[Tuple[int, int], Mapping[str, object]] = {}
    conflicts = 0
    sorted_rows = sorted(
        rows,
        key=lambda row: (
            int(row["layer_id"]),
            int(row["source_frame"]),
            int(row["frame_skip"]),
            str(row["shard"]),
        ),
    )
    for row in sorted_rows:
        key = (int(row["layer_id"]), int(row["source_frame"]))
        previous = selected.get(key)
        if previous is not None and measurement_signature(previous) != measurement_signature(row):
            conflicts += 1
        # For the one-frame RAS overlap, the later-starting shard owns the boundary frame.
        selected[key] = row

    overlap_rows = len(rows) - len(selected)
    return list(selected.values()), len(unique_keys), overlap_rows, conflicts


def sum_fields(rows: Iterable[Mapping[str, object]]) -> Dict[str, int]:
    totals = {field: 0 for field in COUNT_FIELDS}
    for row in rows:
        for field in COUNT_FIELDS:
            totals[field] += int(row[field])
    return totals


def ratio(numerator: int, denominator: int) -> str:
    return f"{numerator / denominator:.10f}" if denominator else "0.0000000000"


def atomic_write_csv(path: Path, fieldnames: Sequence[str], rows: Iterable[Mapping[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    os.replace(temporary, path)


def write_summary(
    output_root: Path,
    sequence: str,
    qp: int,
    rows: Sequence[Mapping[str, object]],
    keep_overlaps: bool,
) -> Path:
    selected, unique_frames, overlap_rows, conflicts = select_rows(rows, keep_overlaps)
    totals = sum_fields(selected)
    shard_count = len({str(row["source_path"]) for row in rows})

    fieldnames = (
        "sequence",
        "qp",
        "mode",
        "cu_count",
        "frequency_all_luma_cus",
        "frequency_intra_pred_luma_cus",
        "share_within_timd",
        "sample_count",
        "coverage_all_luma_samples",
        "coverage_intra_pred_luma_samples",
        "share_within_timd_samples",
        "shard_count",
        "raw_frame_rows",
        "counted_frame_rows",
        "unique_source_frames",
        "overlap_rows_removed",
        "conflicting_overlap_rows",
        "overlap_policy",
        "total_luma_cus",
        "total_intra_pred_luma_cus",
        "total_timd_cus",
        "invalid_timd_cus",
        "timd_merge_available_cus",
        "timd_merge_not_selected_cus",
        "timd_merge_loss_without_flag_cus",
        "timd_merge_flag_coded",
        "timd_merge_flag_zero",
        "timd_merge_flag_one",
        "timd_merge_flag_zero_share",
        "timd_merge_flag_zero_frequency_all_luma_cus",
        "timd_merge_flag_zero_share_of_normal_timd",
    )

    output_rows: List[MutableMapping[str, object]] = []
    for mode, cu_field, sample_field in MODE_FIELDS:
        cu_count = totals[cu_field]
        sample_count = totals[sample_field]
        output_rows.append(
            {
                "sequence": sequence,
                "qp": qp,
                "mode": mode,
                "cu_count": cu_count,
                "frequency_all_luma_cus": ratio(cu_count, totals["luma_cus"]),
                "frequency_intra_pred_luma_cus": ratio(cu_count, totals["intra_pred_luma_cus"]),
                "share_within_timd": ratio(cu_count, totals["timd_total"]),
                "sample_count": sample_count,
                "coverage_all_luma_samples": ratio(sample_count, totals["luma_samples"]),
                "coverage_intra_pred_luma_samples": ratio(sample_count, totals["intra_pred_luma_samples"]),
                "share_within_timd_samples": ratio(sample_count, totals["timd_samples"]),
                "shard_count": shard_count,
                "raw_frame_rows": len(rows),
                "counted_frame_rows": len(selected),
                "unique_source_frames": unique_frames,
                "overlap_rows_removed": overlap_rows,
                "conflicting_overlap_rows": conflicts,
                "overlap_policy": "keep" if keep_overlaps else "deduplicate_prefer_later_shard",
                "total_luma_cus": totals["luma_cus"],
                "total_intra_pred_luma_cus": totals["intra_pred_luma_cus"],
                "total_timd_cus": totals["timd_total"],
                "invalid_timd_cus": totals["timd_invalid"],
                "timd_merge_available_cus": totals["timd_merge_available"],
                "timd_merge_not_selected_cus": totals["timd_merge_not_selected"],
                "timd_merge_loss_without_flag_cus": (
                    totals["timd_merge_not_selected"] - totals["timd_merge_flag_zero"]
                ),
                "timd_merge_flag_coded": totals["timd_merge_flag_coded"],
                "timd_merge_flag_zero": totals["timd_merge_flag_zero"],
                "timd_merge_flag_one": totals["timd_merge_flag_one"],
                "timd_merge_flag_zero_share": ratio(
                    totals["timd_merge_flag_zero"], totals["timd_merge_flag_coded"]
                ),
                "timd_merge_flag_zero_frequency_all_luma_cus": ratio(
                    totals["timd_merge_flag_zero"], totals["luma_cus"]
                ),
                "timd_merge_flag_zero_share_of_normal_timd": ratio(
                    totals["timd_merge_flag_zero"], totals["timd_normal"]
                ),
            }
        )

    output_path = output_root / sequence / f"QP{qp}.csv"
    atomic_write_csv(output_path, fieldnames, output_rows)
    print(
        f"{sequence:24s} QP{qp:>2}: frames={len(selected):>4}, "
        f"TIMD={totals['timd_normal']:>8}, TIMDSAD={totals['timdsad']:>8}, "
        f"TIMDMerge={totals['timd_merge']:>8}, merge_flag_0={totals['timd_merge_flag_zero']:>8}, "
        f"overlaps_removed={overlap_rows}, conflicts={conflicts}"
    )
    return output_path


def parse_expected_qps(value: str) -> set[int]:
    if not value.strip():
        return set()
    try:
        return {int(item.strip()) for item in value.split(",") if item.strip()}
    except ValueError as error:
        raise ValueError(f"invalid --expected-qps value: {value!r}") from error


def main() -> int:
    args = parse_args()
    input_root = args.input_root
    output_root = args.output_root if args.output_root is not None else input_root
    try:
        rows = read_shards(input_root / ".shards")
        expected_qps = parse_expected_qps(args.expected_qps)
    except (FileNotFoundError, OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    groups: Dict[Tuple[str, int], List[Mapping[str, object]]] = defaultdict(list)
    for row in rows:
        groups[(str(row["sequence"]), int(row["qp"]))].append(row)

    written: List[Path] = []
    for (sequence, qp), group_rows in sorted(groups.items()):
        written.append(write_summary(output_root, sequence, qp, group_rows, args.keep_overlaps))

    if expected_qps:
        sequences = sorted({sequence for sequence, _ in groups})
        for sequence in sequences:
            present = {qp for candidate, qp in groups if candidate == sequence}
            missing = sorted(expected_qps - present)
            if missing:
                print(
                    f"warning: {sequence} is missing expected QPs: {','.join(map(str, missing))}",
                    file=sys.stderr,
                )

    print(f"wrote {len(written)} summary files below {output_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
